# .github/workflows/gradle-build-pr.yml
name: Run Gradle on PRs
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          # MongoDB version to use (default "latest")
          mongodb-version: 4.2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run tests
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false
        run: ./gradlew clean build -x composeUp -x composeDown
